[DEFAULT]
# DEP-14 format. Other naming convention are available,
# see DEP-14 for more details.
debian-branch = debian/latest

# Ensure a human always reviews all the debian/changelog entries.
spawn-editor = always

# No need to confirm package name or version at any time, git-buildpackage
# always gets it right.
interactive = False

# Ensure we always target Debian on Debian branches.
dch-opt = --vendor=debian

